project:
  type: website
  output-dir: docs

website:
  title: "R-Cheaties"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: "© 2025 Claudia Spannbauer."
    right: 
      - text: "Impressum"
        href: \#
      - text: "Datenschutz" 
        href: \#
      - text: "Kontakt"
        href: \#
    background: "#f8f9fa"
    foreground: "#6c757d"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true